In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv("Tech_Layoff_Hiring_Trends.csv")

In [3]:
dataset.columns

Index(['record_id', 'company_name', 'industry', 'country', 'company_size',
       'month', 'year', 'layoffs_count', 'layoff_percentage',
       'reason_for_layoffs', 'ai_automation_impact', 'ai_replacement_risk',
       'open_roles', 'hiring_trend', 'remote_jobs_percentage',
       'top_hiring_role', 'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score', 'market_condition'],
      dtype='object')

In [4]:
dataset

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,T11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766,8.4,Market Slowdown,...,Moderate Hiring,15.8,Software Engineer,18.5,-16.8,-0.8,4.0,6.7,5.1,Bull Market
11996,T11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407,13.9,Restructuring,...,Hiring Freeze,51.8,Cloud Engineer,75.3,9.7,-1.7,2.3,7.7,6.2,Stable
11997,T11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576,8.7,Market Slowdown,...,Moderate Hiring,88.8,DevOps Engineer,40.9,11.1,10.7,7.0,8.0,5.1,Recession
11998,T11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039,9.1,Overhiring Correction,...,Moderate Hiring,37.6,Cybersecurity Analyst,24.2,44.2,27.4,8.9,7.3,6.2,Bull Market
11999,T11999,Databricks,AI,Germany,Big Tech,Mar,2026,493,6.6,Restructuring,...,Moderate Hiring,32.6,ML Engineer,45.1,-9.3,-7.2,2.9,4.9,6.0,Bull Market

In [5]:
dataset.isnull().sum()

record_id                 0
company_name              0
industry                  0
country                   0
company_size              0
month                     0
year                      0
layoffs_count             0
layoff_percentage         0
reason_for_layoffs        0
ai_automation_impact      0
ai_replacement_risk       0
open_roles                0
hiring_trend              0
remote_jobs_percentage    0
top_hiring_role           0
stock_growth_percent      0
revenue_growth_percent    0
salary_budget_change      0
ai_adoption_level         0
employee_sentiment        0
job_security_score        0
market_condition          0
dtype: int64

In [6]:
dataset.drop("record_id",axis=1,inplace=True)

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

dataset['market_condition'] = le.fit_transform(dataset['market_condition'])

# One-Hot Encoding Columns
one_hot_cols = [
    'company_name',
    'industry',
    'country',
    'reason_for_layoffs',
    'hiring_trend',
    'top_hiring_role',
    'company_size',
    'month'
]

# One-Hot Encoding
dataset = pd.get_dummies(
    dataset,
    columns=one_hot_cols,
    drop_first=True,dtype=int
)

# Split X and y
indep_X= dataset.drop('market_condition', axis=1)
dep_Y = dataset['market_condition']

print(indep_X.shape)
print(dep_Y.shape)
print(dataset.head())

(12000, 71)
(12000,)
   year  layoffs_count  layoff_percentage  ai_automation_impact  \
0  2026            860                1.8                   6.4
1  2024            955                1.8                   0.9
2  2025          18912                9.5                   7.1
3  2025          18159                9.1                  10.4
4  2025            815                3.3                  11.4

   ai_replacement_risk  open_roles  remote_jobs_percentage  \
0                  5.0        5426                    46.7
1                  1.1        9666                    58.9
2                  3.9         437                    85.4
3                  7.4        1075                    44.0
4                 10.0         537                    53.2

   stock_growth_percent  revenue_growth_percent  salary_budget_change  ...  \
0                 -25.7                    30.3                   4.9  ...
1                  -5.6                     6.1                   1.5  ...
2                   7.0                   -23.6                 -14.9  ...
3                  31.6                   -22.3                  -1.6  ...
4                  85.3                    26.6                   9.8  ...

   month_Dec  month_Feb  month_Jan  month_Jul  month_Jun  month_Mar  \
0          0          0          0          0          0          1
1          0          1          0          0          0          0
2          0          0          0          0          0          0
3          0          0          0          0          1          0
4          0          1          0          0          0          0

   month_May  month_Nov  month_Oct  month_Sep
0          0          0          0          0
1          0          0          0          0
2          0          0          0          0
3          0          0          0          0
4          0          0          0          0

[5 rows x 72 columns]

In [8]:
dataset['market_condition'].value_counts()

2    4078
0    4019
1    3903
Name: market_condition, dtype: int64

In [9]:
dataset

,year,layoffs_count,layoff_percentage,ai_automation_impact,ai_replacement_risk,open_roles,remote_jobs_percentage,stock_growth_percent,revenue_growth_percent,salary_budget_change,...,month_Dec,month_Feb,month_Jan,month_Jul,month_Jun,month_Mar,month_May,month_Nov,month_Oct,month_Sep
0,2026,860,1.8,6.4,5.0,5426,46.7,-25.7,30.3,4.9,...,0,0,0,0,0,1,0,0,0,0
1,2024,955,1.8,0.9,1.1,9666,58.9,-5.6,6.1,1.5,...,0,1,0,0,0,0,0,0,0,0
2,2025,18912,9.5,7.1,3.9,437,85.4,7.0,-23.6,-14.9,...,0,0,0,0,0,0,0,0,0,0
3,2025,18159,9.1,10.4,7.4,1075,44.0,31.6,-22.3,-1.6,...,0,0,0,0,1,0,0,0,0,0
4,2025,815,3.3,11.4,10.0,537,53.2,85.3,26.6,9.8,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2024,766,8.4,5.6,5.3,5364,15.8,18.5,-16.8,-0.8,...,0,0,0,0,0,1,0,0,0,0
11996,2026,3407,13.9,3.4,5.7,3865,51.8,75.3,9.7,-1.7,...,0,0,0,1,0,0,0,0,0,0
11997,2025,2576,8.7,8.3,8.7,544,88.8,40.9,11.1,10.7,...,0,0,0,0,0,0,0,0,0,1
11998,2025,1039,9.1,9.1,10.0,2243,37.6,24.2,44.2,27.4,...,0,0,0,0,0,0,0,0,0,1
11999,2026,493,6.6,2.4,3.2,6987,32.6,45.1,-9.3,-7.2,...,0,0,0,0,0,1,0,0,0,0

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [14]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_macro') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

C:\Anaconda3\envs\web\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.

Fitting 3 folds for each of 8 candidates, totalling 24 fits

[Parallel(n_jobs=-1)]: Done   2 out of  24 | elapsed:    4.4s remaining:   49.4s
[Parallel(n_jobs=-1)]: Done  11 out of  24 | elapsed:    5.0s remaining:    5.9s
[Parallel(n_jobs=-1)]: Done  20 out of  24 | elapsed:    7.2s remaining:    1.4s
[Parallel(n_jobs=-1)]: Done  24 out of  24 | elapsed:    7.4s finished
C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt'],
                         'n_estimators': [10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_macro', verbose=3)

In [15]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [16]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.270178,0.007116,0.029256,0.015501,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.849019,0.862481,0.875892,0.862461,0.010972,8
1,2.013374,0.027007,0.093092,0.000401,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.886408,0.891330,0.888689,0.888808,0.002011,3
2,0.255875,0.008849,0.027977,0.006025,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.871574,0.876751,0.881622,0.876648,0.004103,5
3,1.985462,0.013362,0.092410,0.002727,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.891101,0.892764,0.890629,0.891498,0.000916,1
4,0.316805,0.014655,0.018357,0.001437,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.866102,0.868003,0.861140,0.865082,0.002893,7
5,2.560381,0.021203,0.091919,0.000954,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.886400,0.888944,0.887490,0.887611,0.001042,4
6,0.314447,0.022719,0.015008,0.000805,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.877281,0.870730,0.867620,0.871878,0.004027,6
7,2.459726,0.020941,0.089310,0.005478,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.890385,0.894300,0.887976,0.890887,0.002606,2

In [19]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}: 0.9060842471570841

In [20]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[1311    0    7]
 [   5 1254   96]
 [ 234   30 1063]]

In [21]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.85      0.99      0.91      1318
           1       0.98      0.93      0.95      1355
           2       0.91      0.80      0.85      1327

    accuracy                           0.91      4000
   macro avg       0.91      0.91      0.91      4000
weighted avg       0.91      0.91      0.91      4000

In [25]:
import pickle

pickle.dump(grid, open("rf_model.sav", "wb"))
pickle.dump(sc, open("scaler.sav", "wb"))
pickle.dump(indep_X.columns.tolist(), open("columns.sav", "wb"))

print("Files Saved Successfully")

Files Saved Successfully

In [26]:
import pandas as pd
import pickle

# Load files
model = pickle.load(open("rf_model.sav", "rb"))
scaler = pickle.load(open("scaler.sav", "rb"))
columns = pickle.load(open("columns.sav", "rb"))

# User Inputs
company_name = input("Company Name: ")
industry = input("Industry: ")
country = input("Country: ")
company_size = input("Company Size: ")
month = input("Month: ")

year = float(input("Year: "))
layoffs_count = float(input("Layoffs Count: "))
layoff_percentage = float(input("Layoff Percentage: "))

reason_for_layoffs = input("Reason For Layoffs: ")

ai_automation_impact = float(input("AI Automation Impact: "))
ai_replacement_risk = float(input("AI Replacement Risk: "))
open_roles = float(input("Open Roles: "))

hiring_trend = input("Hiring Trend: ")

remote_jobs_percentage = float(input("Remote Jobs Percentage: "))

top_hiring_role = input("Top Hiring Role: ")

stock_growth_percent = float(input("Stock Growth Percent: "))
revenue_growth_percent = float(input("Revenue Growth Percent: "))
salary_budget_change = float(input("Salary Budget Change: "))

ai_adoption_level = float(input("AI Adoption Level: "))
employee_sentiment = float(input("Employee Sentiment: "))
job_security_score = float(input("Job Security Score: "))

# Create DataFrame
new_data = pd.DataFrame({
    'company_name':[company_name],
    'industry':[industry],
    'country':[country],
    'company_size':[company_size],
    'month':[month],
    'year':[year],
    'layoffs_count':[layoffs_count],
    'layoff_percentage':[layoff_percentage],
    'reason_for_layoffs':[reason_for_layoffs],
    'ai_automation_impact':[ai_automation_impact],
    'ai_replacement_risk':[ai_replacement_risk],
    'open_roles':[open_roles],
    'hiring_trend':[hiring_trend],
    'remote_jobs_percentage':[remote_jobs_percentage],
    'top_hiring_role':[top_hiring_role],
    'stock_growth_percent':[stock_growth_percent],
    'revenue_growth_percent':[revenue_growth_percent],
    'salary_budget_change':[salary_budget_change],
    'ai_adoption_level':[ai_adoption_level],
    'employee_sentiment':[employee_sentiment],
    'job_security_score':[job_security_score]
})

# One Hot Encoding
new_data = pd.get_dummies(new_data)

# Match Training Columns
new_data = new_data.reindex(columns=columns, fill_value=0)

# Scaling
new_data_scaled = scaler.transform(new_data)

# Prediction
prediction = model.predict(new_data_scaled)

print("\n Prediction : 0 - Bull Market")
print("\n              1 - Recession")
print("\n              2 - Stable")


print("\n Prediction =", prediction[0])

Company Name: apple
Industry: technology
Country: usa
Company Size: midsize
Month: apr
Year: 2025
Layoffs Count: 18912
Layoff Percentage: 9.1
Reason For Layoffs: cost cutting
AI Automation Impact: 8.78
AI Replacement Risk: 7.56
Open Roles: 8795
Hiring Trend: ai engineer
Remote Jobs Percentage: 5.45
Top Hiring Role: ml engineer
Stock Growth Percent: 2.89
Revenue Growth Percent: 5.6
Salary Budget Change: 4.5
AI Adoption Level: 7.8
Employee Sentiment: 5.6
Job Security Score: 4.6

 Prediction : 0 - Bull Market

              1 - Recession

              2 - Stable

 Prediction = 1

C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):