In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv("Tech_Layoff_Hiring_Trends.csv")

In [4]:
dataset.columns

Index(['record_id', 'company_name', 'industry', 'country', 'company_size',
       'month', 'year', 'layoffs_count', 'layoff_percentage',
       'reason_for_layoffs', 'ai_automation_impact', 'ai_replacement_risk',
       'open_roles', 'hiring_trend', 'remote_jobs_percentage',
       'top_hiring_role', 'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score', 'market_condition'],
      dtype='object')

In [5]:
dataset.drop("record_id",axis=1,inplace=True)

In [6]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
dataset['market_condition']=le.fit_transform(dataset['market_condition'])

In [7]:
one_hot_col=['company_name',
    'industry',
    'country',
    'reason_for_layoffs',
    'hiring_trend',
    'top_hiring_role',
    'company_size',
    'month']

dataset=pd.get_dummies(dataset,columns=one_hot_col,drop_first=True).astype(float)

In [32]:
dataset

,year,layoffs_count,layoff_percentage,ai_automation_impact,ai_replacement_risk,open_roles,remote_jobs_percentage,stock_growth_percent,revenue_growth_percent,salary_budget_change,...,month_Dec,month_Feb,month_Jan,month_Jul,month_Jun,month_Mar,month_May,month_Nov,month_Oct,month_Sep
0,2026.0,860.0,1.8,6.4,5.0,5426.0,46.7,-25.7,30.3,4.9,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,2024.0,955.0,1.8,0.9,1.1,9666.0,58.9,-5.6,6.1,1.5,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2025.0,18912.0,9.5,7.1,3.9,437.0,85.4,7.0,-23.6,-14.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2025.0,18159.0,9.1,10.4,7.4,1075.0,44.0,31.6,-22.3,-1.6,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,2025.0,815.0,3.3,11.4,10.0,537.0,53.2,85.3,26.6,9.8,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2024.0,766.0,8.4,5.6,5.3,5364.0,15.8,18.5,-16.8,-0.8,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11996,2026.0,3407.0,13.9,3.4,5.7,3865.0,51.8,75.3,9.7,-1.7,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11997,2025.0,2576.0,8.7,8.3,8.7,544.0,88.8,40.9,11.1,10.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11998,2025.0,1039.0,9.1,9.1,10.0,2243.0,37.6,24.2,44.2,27.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11999,2026.0,493.0,6.6,2.4,3.2,6987.0,32.6,45.1,-9.3,-7.2,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [9]:
indep_X= dataset.drop('market_condition', axis=1)
dep_Y = dataset['market_condition']

print(indep_X.shape)
print(dep_Y.shape)

(12000, 71)
(12000,)

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [15]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_macro') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

C:\Anaconda3\envs\web\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.

Fitting 3 folds for each of 8 candidates, totalling 24 fits

[Parallel(n_jobs=-1)]: Done   2 out of  24 | elapsed:    4.7s remaining:   53.1s
[Parallel(n_jobs=-1)]: Done  11 out of  24 | elapsed:    5.3s remaining:    6.3s
[Parallel(n_jobs=-1)]: Done  20 out of  24 | elapsed:    7.4s remaining:    1.4s
[Parallel(n_jobs=-1)]: Done  24 out of  24 | elapsed:    7.7s finished
C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt'],
                         'n_estimators': [10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_macro', verbose=3)

In [16]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [17]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.261224,0.011968,0.021289,0.002862,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.843959,0.856455,0.871077,0.857160,0.011082,8
1,2.024823,0.021773,0.093555,0.000958,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.892260,0.892630,0.892089,0.892326,0.000226,1
2,0.275014,0.005482,0.023093,0.008564,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.861285,0.872834,0.867561,0.867225,0.004721,7
3,2.054686,0.015352,0.090651,0.001930,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.887617,0.891083,0.886094,0.888265,0.002087,4
4,0.320412,0.007301,0.017315,0.000520,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.873812,0.864562,0.870336,0.869571,0.003815,6
5,2.549632,0.025566,0.087633,0.002921,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.889765,0.891474,0.885663,0.888968,0.002438,3
6,0.332346,0.019763,0.015132,0.000367,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.873692,0.871694,0.868644,0.871344,0.002076,5
7,2.494188,0.029152,0.089627,0.001909,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.892536,0.888607,0.890908,0.890684,0.001612,2

In [20]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.90609709186791

In [21]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[1316    0    2]
 [   5 1257   93]
 [ 234   37 1056]]

In [22]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

         0.0       0.85      1.00      0.92      1318
         1.0       0.97      0.93      0.95      1355
         2.0       0.92      0.80      0.85      1327

    accuracy                           0.91      4000
   macro avg       0.91      0.91      0.91      4000
weighted avg       0.91      0.91      0.91      4000

In [31]:
grid.predict([[]])

ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required.